# Basic Site Settings
locale                   : "en-US"
title                    : "Xiangyu Cui's Profile"
title_separator          : "-"
name                     : &name "Xiangyu Cui"
description              : &description "Passionate about coding and multiagent systems."
url                      : https://academicpages.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : ""
repository               : "Xiangyu2141480/Xiangyu2141480.github.io"

# Site Author
author:
  avatar           : "profile.png"
  name             : "Xiangyu Cui"
  bio              : "Passionate about coding and currently exploring Multiagent Models/Algorithms."
  location         : "Red Brick University"
  email            : "2794555236@qq.com"

  # Academic websites
  googlescholar    : "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  orcid            : "http://orcid.org/yourorcidurl" # Update with your ORCID if you have one
  github           : "Xiangyu2141480"
  kaggle           : "xiangyucui25"

# Publication Category
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# Site Settings
teaser                   : 
breadcrumbs              : false 
words_per_minute         : 160
future                   : true
read_more                : "disabled" 
talkmap_link             : false 

# Analytics
analytics:
  provider               :  "false"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# Outputting
permalink: /:categories/:title/
timezone: Etc/UTC 

# HTML Compression
compress_html:
  clippings: all
